CREATE PLUGGABLE DATABASE CinemaNet ADMIN USER admin_user IDENTIFIED BY admin_password
  FILE_NAME_CONVERT = ('D:\ORACLEXE_APP\ORADATA\XE\PDBSEED\', 'D:\Документы БГТУ\Kursach');

ALTER SESSION SET CONTAINER = CinemaNet;

ALTER PLUGGABLE DATABASE CinemaNet OPEN;

ALTER SESSION SET CONTAINER=CDB$ROOT;

CREATE TABLE HALLS (
    HALL_NUMBER NUMBER PRIMARY KEY,
    SEATS_COUNT NUMBER
);

CREATE TABLE ACTORS (
    NAME VARCHAR2(50) PRIMARY KEY,
    BIRTH_DATE DATE
);

CREATE TABLE CLIENTS (
    ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    EMAIL VARCHAR2(50),
    PHONE VARCHAR2(50)
);

CREATE TABLE DIRECTORS (
    NAME VARCHAR2(50) PRIMARY KEY,
    BIRTH_DATE DATE
);

CREATE TABLE TICKETS (
    ID NUMBER PRIMARY KEY,
    FILM_NAME VARCHAR2(50),
    HALL_ID NUMBER,
    CLIENT_ID NUMBER,
    PRICE NUMBER,
    START_TIME TIMESTAMP,
    FOREIGN KEY (HALL_ID) REFERENCES HALLS(HALL_NUMBER),
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);

CREATE TABLE REVIEWS (
    FILM_NAME VARCHAR2(50),
    CLIENT_ID NUMBER,
    RATING NUMBER,
    REVIEW_TEXT VARCHAR2(500) PRIMARY KEY,
    FOREIGN KEY (CLIENT_ID) REFERENCES CLIENTS(ID)
);

CREATE TABLE FILMS (
    TITLE VARCHAR2(50) PRIMARY KEY,
    DESCRIPTION VARCHAR2(50),
    RELEASE_DATE DATE,
    DURATION NUMBER,
    AGE_RESTRICTION VARCHAR2(50),
    FILM_ACTOR_1 VARCHAR2(50),
    FILM_ACTOR_2 VARCHAR2(50),
    FILM_ACTOR_3 VARCHAR2(50),
    FILM_DIRECTORS VARCHAR2(50),
    FILM_REVIEW VARCHAR2(500),
    GENRE VARCHAR2(50),
    POSTER BFILE,
    FOREIGN KEY (FILM_ACTOR_1) REFERENCES ACTORS(NAME),
    FOREIGN KEY (FILM_ACTOR_2) REFERENCES ACTORS(NAME),
    FOREIGN KEY (FILM_ACTOR_3) REFERENCES ACTORS(NAME),
    FOREIGN KEY (FILM_DIRECTORS) REFERENCES DIRECTORS(NAME),
    FOREIGN KEY (FILM_REVIEW) REFERENCES REVIEWS(REVIEW_TEXT)
);