ALTER SESSION SET "_oracle_script" = TRUE;
CREATE TABLESPACE TS_TRA 
DATAFILE 'TS_TRA.dat'
SIZE 7M
AUTOEXTEND ON NEXT 5M MAXSIZE 30M;

CREATE TEMPORARY TABLESPACE TS_TRA_TEMP 
TEMPFILE 'TS_TRA_TEMP.dat'
SIZE 5M
AUTOEXTEND ON NEXT 3M MAXSIZE 20M;

SELECT TABLESPACE_NAME FROM dba_tablespaces;
select file_name, tablespace_name FROM DBA_DATA_FILES;
